name: poc-battlepass
version: '1.0.3-POC'
author: Kstars
main: fr.kstars.battlepass.BattlepassPlugin
api-version: '1.21'
description: An BattlePass plugin
commands:
  battlepass:
    description: Open the battlepass interface
    aliases: bp
    usage: /battlepass
  battlepass-admin:
    description: Commands for server administrators
    usage: /battlepass-admin <option> [args]
    aliases: bpa
    permission: battlepass.admin